export const newSystemStarterTemplates = [
  {
    key: "v2-arc-ranger",
    unlockLevel: 1,
    name: "Arc Ranger",
    role: "Poke / tempo",
    description: "High-frequency pulse module configuration for safe lane control and reliable confirms.",
    tags: ["starter-v2", "poke", "control"],
    build: {
      weapon: "pulse",
      modules: ["boltLinkJavelin", "orbitalDistorter", "ghostDriftModule"],
      implants: ["reactiveArmor"],
      core: "phantomCore",
    },
  },
  {
    key: "v2-breach-hammer",
    unlockLevel: 1,
    name: "Breach Hammer",
    role: "Engage / punish",
    description: "Shotgun engage build with focused close-range punish modules.",
    tags: ["starter-v2", "burst", "engage"],
    build: {
      weapon: "shotgun",
      modules: ["vGripHarpoon", "boltLinkJavelin", "hexPlateProjector"],
      implants: ["critScanRelay"],
      core: "phantomCore",
    },
  },
  {
    key: "v2-deadeye-circuit",
    unlockLevel: 3,
    name: "Deadeye Circuit",
    role: "Spacing / pick",
    description: "Axe skirmish preset tuned for tactical precision and module-driven picks.",
    tags: ["starter-v2", "sniper", "spacing"],
    build: {
      weapon: "axe",
      modules: ["ghostDriftModule", "voidCoreSingularity", "boltLinkJavelin"],
      implants: ["scavengerPlates"],
      core: "phantomCore",
    },
  },
  {
    key: "v2-warden-siege",
    unlockLevel: 5,
    name: "Warden Siege",
    role: "Frontline / control",
    description: "Staff frontline preset utilizing heavy defensive modules.",
    tags: ["starter-v2", "tank", "control"],
    build: {
      weapon: "staff",
      modules: ["hexPlateProjector", "orbitalDistorter", "ghostDriftModule"],
      implants: ["scavengerPlates"],
      core: "rebootProtocol",
    },
  },
  {
    key: "v2-toxic-surge",
    unlockLevel: 8,
    name: "Toxic Surge",
    role: "Duel / sustain",
    description: "Injector sustain preset built for high-tempo module cycles.",
    tags: ["starter-v2", "hybrid", "aggro"],
    build: {
      weapon: "injector",
      modules: ["voidCoreSingularity", "ghostDriftModule", "hexPlateProjector"],
      implants: ["bioDrainLink"],
      core: "empCataclysmCore",
    },
  },
  {
    key: "v2-colossus-breaker",
    unlockLevel: 12,
    name: "Colossus Breaker",
    role: "Late game / siege",
    description: "Cannon finisher preset with peak reactor core pressure.",
    tags: ["starter-v2", "burst", "control"],
    build: {
      weapon: "cannon",
      modules: ["orbitalDistorter", "voidCoreSingularity", "ghostDriftModule"],
      implants: ["seqShotCalculator"],
      core: "phantomCore",
    },
  },
];

