// Game configuration constants
export const arena = { width: 1600, height: 900 };


export const config = {
  playerSpeed: 420,
  playerAcceleration: 4400,
  playerFriction: 3600,
  playerRadius: 18,
  playerMaxHp: 280,
  dashSpeed: 1200,
  dashDuration: 0.17,
  dashInvulnerability: 0.24,
  dashCooldown: 1.8,
  fireRate: 0.084,
  bulletSpeed: 1320,
  bulletLife: 1,
  pulseDamage: 10,
  pulseMagazineSize: 12,
  pulseReloadTime: 1.18,
  axeComboReset: 0.72,
  axeCommitSpeed: 940,
  axeCommitDuration: 0.12,
  javelinCooldown: 3.4,
  javelinChargeThreshold: 0.45,
  javelinTapSpeed: 1220,
  javelinTapDamage: 40,
  javelinTapRadius: 11,
  javelinTapSlow: 0.26,
  javelinTapSlowDuration: 0.7,
  javelinHoldSpeed: 980,
  javelinHoldDamage: 58,
  javelinHoldRadius: 16,
  javelinHoldStun: 0.5,
  fieldCooldown: 3.6,
  fieldChargeThreshold: 0.45,
  fieldTapDuration: 1.2,
  fieldTapRadius: 92,
  fieldTapSlow: 0.45,
  fieldTapDamageReduction: 0.45,
  fieldTapMoveBoost: 1.16,
  fieldTapMoveBoostDuration: 0.9,
  fieldHoldDuration: 2.2,
  fieldHoldRadius: 132,
  fieldHoldSlow: 0.62,
  portalReuseCooldown: 10,
  grappleCooldown: 4.2,
  shieldCooldown: 5.2,
  boosterCooldown: 6.5,
  ultimateCooldown: 14,
  enemyRadius: 20,
  enemyMaxHp: 380,
  enemySpeed: 246,
  enemyDodgeSpeed: 780,
  enemyDodgeDuration: 0.17,
  enemyDodgeCooldown: 1.6,
  runePoints: 15,
};


export const sandboxModes = {
  duel: {
    key: "duel",
    name: "Duel Map",
    subtitle: "One hunter bot with full combat behavior.",
  },
  training: {
    key: "training",
    name: "Training Map",
    subtitle: "Five static bots lined up for range, cleave, and status tests.",
  },
};


export const abilityConfig = {
  dash: {
    tapDuration: config.dashDuration,
    tapInvulnerability: config.dashInvulnerability,
    tapSpeed: config.dashSpeed,
    holdThreshold: 0.16,
    holdDuration: 0.28,
    holdInvulnerability: 0.34,
    holdSpeed: 1320,
    trailColor: "#9df4b7",
  },
  javelin: {
    cooldown: config.javelinCooldown,
    chargeThreshold: config.javelinChargeThreshold,
    maxCharge: 1,
    tap: {
      speed: config.javelinTapSpeed,
        damage: config.javelinTapDamage,
        radius: config.javelinTapRadius,
        slow: config.javelinTapSlow,
        slowDuration: config.javelinTapSlowDuration,
        color: "#8fe8ff",
        glow: "#c4f8ff",
        trail: "#6ad8ff",
      },
    hold: {
        speed: config.javelinHoldSpeed,
        damage: config.javelinHoldDamage,
        radius: config.javelinHoldRadius,
        stun: config.javelinHoldStun,
        color: "#ffd77e",
        glow: "#fff0b4",
        trail: "#ffc85a",
    },
  },
  field: {
    cooldown: config.fieldCooldown,
    chargeThreshold: config.fieldChargeThreshold,
    tap: {
      duration: config.fieldTapDuration,
      radius: config.fieldTapRadius,
      slow: config.fieldTapSlow,
      damageReduction: config.fieldTapDamageReduction,
      anchor: "player",
      color: "#89c8ff",
      glow: "#a8ddff",
    },
    hold: {
      duration: config.fieldHoldDuration,
      radius: config.fieldHoldRadius,
      slow: config.fieldHoldSlow,
      damageReduction: 0,
      anchor: "world",
      color: "#95b5ff",
      glow: "#bed1ff",
    },
  },
};

