// Game configuration constants
export const arena = { width: 1600, height: 900 };

export const config = {
  playerSpeed: 420,
  playerAcceleration: 4400,
  playerFriction: 3600,
  playerRadius: 18,
  playerMaxHp: 280,
  dashSpeed: 1200,
  dashDuration: 0.17,
  dashInvulnerability: 0.24,
  dashCooldown: 1.8,
  cameraLookAheadX: 268,
  cameraLookAheadY: 154,
  cameraLookDeadzone: 0.22,
  cameraLookSmoothing: 5.2,
  cameraLookInputSmoothing: 3.4,
  cameraCatchupDistance: 220,
  cameraCatchupBoost: 4.8,
  cameraPlayerSafeRatioX: 0.22,
  cameraPlayerSafeRatioY: 0.16,
  fireRate: 0.088,
  bulletSpeed: 1320,
  bulletLife: 1,
  pulseDamage: 9,
  pulseMagazineSize: 12,
  pulseReloadTime: 1.18,
  sniperBaseCooldown: 1.08,
  sniperChargeTime: 0.9,
  sniperMinDamage: 28,
  sniperMaxDamage: 62,
  sniperProjectileSpeed: 1880,
  sniperChargedProjectileSpeed: 2620,
  sniperTravelBonusRange: 1120,
  sniperSlow: 0.14,
  sniperSlowDuration: 0.42,
  sniperChargedSnare: 1,
  sniperChargedSnareDuration: 0.42,
  axeComboReset: 3,
  axeCommitSpeed: 940,
  axeCommitDuration: 0.12,
  javelinCooldown: 4.2,
  javelinSpeed: 1380,
  javelinDamage: 38,
  javelinRadius: 11,
  javelinRange: 760,
  javelinSlow: 0.34,
  javelinSlowDuration: 1.5,
  javelinRecastDistance: 42,
  pulseBurstCooldown: 4.1,
  pulseBurstMissiles: 5,
  pulseBurstProjectileSpeed: 1280,
  pulseBurstLifetime: 0.72,
  pulseBurstBaseDamage: 7.5,
  pulseBurstDamageGrowth: 1.26,
  pulseBurstGuideTurnRate: 6.2,
  pulseBurstGuideDot: 0.48,
  pulseBurstBurnDuration: 1.8,
  fieldCooldown: 3.6,
  fieldChargeThreshold: 0.45,
  fieldTapDuration: 1.35,
  fieldTapRadius: 118,
  fieldTapSlow: 0.28,
  fieldTapDamageReduction: 0.28,
  fieldTapMoveBoost: 1.16,
  fieldTapMoveBoostDuration: 0.9,
  fieldTapProjectileSlowEdge: 0.34,
  fieldTapProjectileSlowCore: 0.58,
  fieldHoldDuration: 2.5,
  fieldHoldRadius: 176,
  fieldHoldSlow: 0.34,
  fieldHoldProjectileSlowEdge: 0.44,
  fieldHoldProjectileSlowCore: 0.72,
  portalReuseCooldown: 10,
  grappleCooldown: 5.6,
  grappleRange: 620,
  grappleWidth: 20,
  grappleProjectileSpeed: 1360,
  grappleProjectileRadius: 11,
  grapplePullSpeed: 920,
  grapplePullDistance: 170,
  grappleSnare: 1,
  grappleSnareDuration: 0.72,
  gravityWellCooldown: 6.2,
  gravityWellRadius: 126,
  gravityWellDuration: 2.4,
  gravityWellSlow: 0.26,
  gravityWellPullStrength: 124,
  energyParryStartup: 0.04,
  energyParryWindow: 1.2,
  energyParryFailRecovery: 0.15,
  energyParryCooldown: 9,
  energyParryShield: 18,
  energyParryShieldDuration: 2,
  energyParryMoveBonus: 0.2,
  energyParryMoveDuration: 1,
  energyParryHitBonusDamage: 14,
  energyParryHitBonusDuration: 1.5,
  energyParryTeleportOffset: 20,
  phaseShiftCooldown: 7.2,
  phaseShiftDuration: 0.62,
  shieldCooldown: 5.8,
  shieldValue: 24,
  shieldDuration: 2.2,
  shieldBreakRefund: 0.3,
  boosterCooldown: 6.5,
  ultimateCooldown: 14,
  phantomDuration: 4,
  phantomReplayDelay: 0.16,
  phantomActionDelay: 0.16,
  phantomDamageScale: 0.3,
  phantomHpScale: 0.3,
  phantomShieldScale: 0.3,
  phantomHealScale: 0.3,
  phantomStatusScale: 0.3,
  lancePrimaryRange: 228,
  lancePrimaryWidth: 18,
  lancePrimaryDamage: 44,
  lancePrimaryCooldown: 0.64,
  lancePrimarySlow: 0.24,
  lancePrimarySlowDuration: 0.28,
  lanceAltRange: 196,
  lanceAltWidth: 26,
  lanceAltDamage: 62,
  lanceAltCooldown: 1.06,
  lanceAltShockDuration: 0.42,
  cannonPrimaryDamage: 20,
  cannonPrimarySpeed: 760,
  cannonPrimaryCooldown: 0.92,
  cannonPrimaryRadius: 9,
  cannonSplashRadius: 84,
  cannonSplashDamage: 34,
  cannonBurnDuration: 1.8,
  cannonBurnMagnitude: 0.14,
  cannonMaxRange: 580,
  cannonChargeTime: 0.74,
  cannonAltDamage: 28,
  cannonAltSpeed: 640,
  cannonAltCooldown: 1.2,
  cannonAltRadius: 10,
  cannonFreezeDuration: 2.6,
  cannonFreezeMagnitude: 0.24,
  cannonChargedPushMax: 78,
  cannonChargedPushMin: 22,
  burnTickInterval: 0.45,
  burnTickDamage: 2.8,
  lastStandDuration: 3,
  lastStandMoveBonus: 0.22,
  lastStandHasteBonus: 0.28,
  precisionMomentumMaxStacks: 3,
  precisionMomentumDamagePerStack: 0.08,
  enemyRadius: 20,
  enemyMaxHp: 380,
  enemySpeed: 246,
  enemyDodgeSpeed: 780,
  enemyDodgeDuration: 0.17,
  enemyDodgeCooldown: 1.6,
  survivalWavePause: 2.1,
  survivalWaveIntermission: 3,
  runePoints: 15,
};

export const sandboxModes = {
  duel: {
    key: "duel",
    name: "Arena (1v1)",
    subtitle: "One hunter bot, fair spawns, full duel behavior.",
  },
  survival: {
    key: "survival",
    name: "Survival Mode",
    subtitle: "Escalating solo waves against adaptive hunter builds.",
  },
  training: {
    key: "training",
    name: "Training Lab",
    subtitle: "Static targets and instant rebuilds for values, spacing, and combo tests.",
  },
};

export const abilityConfig = {
  dash: {
    tapDuration: config.dashDuration,
    tapInvulnerability: config.dashInvulnerability,
    tapSpeed: config.dashSpeed,
    holdThreshold: 0.16,
    holdDuration: 0.28,
    holdInvulnerability: 0.34,
    holdSpeed: 1320,
    trailColor: "#9df4b7",
  },
  javelin: {
    cooldown: config.javelinCooldown,
    speed: config.javelinSpeed,
    damage: config.javelinDamage,
    radius: config.javelinRadius,
    range: config.javelinRange,
    slow: config.javelinSlow,
    slowDuration: config.javelinSlowDuration,
    recastDistance: config.javelinRecastDistance,
    color: "#8fe8ff",
    glow: "#d9fbff",
    trail: "#7ce5ff",
  },
  field: {
    cooldown: config.fieldCooldown,
    chargeThreshold: config.fieldChargeThreshold,
    tap: {
      duration: config.fieldTapDuration,
      radius: config.fieldTapRadius,
      slow: config.fieldTapSlow,
      damageReduction: config.fieldTapDamageReduction,
      projectileSlowEdge: config.fieldTapProjectileSlowEdge,
      projectileSlowCore: config.fieldTapProjectileSlowCore,
      anchor: "player",
      color: "#89c8ff",
      glow: "#a8ddff",
    },
    hold: {
      duration: config.fieldHoldDuration,
      radius: config.fieldHoldRadius,
      slow: config.fieldHoldSlow,
      damageReduction: 0,
      projectileSlowEdge: config.fieldHoldProjectileSlowEdge,
      projectileSlowCore: config.fieldHoldProjectileSlowCore,
      anchor: "world",
      color: "#95b5ff",
      glow: "#bed1ff",
    },
  },
  castTimes: {
    javelin: 0.18,
    pulseBurst: 0.15,
    railShot: 0.22,
    chainLightning: 0.16,
    gravityWell: 0.21,
    magneticField: 0.19,
    magneticGrapple: 0.18,
  },
};
