// Game configuration constants
export const arena = { width: 1600, height: 900 };

export const config = {
  playerSpeed: 420,
  playerAcceleration: 4400,
  playerFriction: 3600,
  playerRadius: 18,
  playerMaxHp: 280,
  dashSpeed: 1200,
  dashDuration: 0.17,
  dashInvulnerability: 0.24,
  dashCooldown: 1.8,
  cameraLookAheadX: 268,
  cameraLookAheadY: 154,
  cameraLookDeadzone: 0.22,
  cameraLookSmoothing: 5.2,
  cameraLookInputSmoothing: 3.4,
  cameraCatchupDistance: 220,
  cameraCatchupBoost: 4.8,
  cameraPlayerSafeRatioX: 0.22,
  cameraPlayerSafeRatioY: 0.16,
  fireRate: 0.088,
  bulletSpeed: 1320,
  bulletLife: 1,
  pulseDamage: 9,
  pulseMagazineSize: 12,
  pulseReloadTime: 1.18,
  sniperBaseCooldown: 1.08,
  sniperChargeTime: 0.9,
  sniperMinDamage: 28,
  sniperMaxDamage: 62,
  sniperProjectileSpeed: 1880,
  sniperChargedProjectileSpeed: 2620,
  sniperTravelBonusRange: 1120,
  sniperSlow: 0.14,
  sniperSlowDuration: 0.42,
  sniperChargedSnare: 1,
  sniperChargedSnareDuration: 0.42,
  axeComboReset: 3,
  axeCommitSpeed: 940,
  axeCommitDuration: 0.12,
  boltLinkJavelinCooldown: 4.2,
  boltLinkJavelinSpeed: 1380,
  boltLinkJavelinDamage: 38,
  boltLinkJavelinRadius: 11,
  boltLinkJavelinRange: 760,
  boltLinkJavelinSlow: 0.34,
  boltLinkJavelinSlowDuration: 1.5,
  boltLinkJavelinRecastDistance: 42,
  swarmMissileRackCooldown: 4.1,
  swarmMissileRackMissiles: 5,
  swarmMissileRackProjectileSpeed: 1280,
  swarmMissileRackLifetime: 0.72,
  swarmMissileRackBaseDamage: 7.5,
  swarmMissileRackDamageGrowth: 1.26,
  swarmMissileRackGuideTurnRate: 6.2,
  swarmMissileRackGuideDot: 0.48,
  swarmMissileRackBurnDuration: 1.8,
  orbitalDistorterCooldown: 3.6,
  orbitalDistorterChargeThreshold: 0.45,
  orbitalDistorterTapDuration: 1.35,
  orbitalDistorterTapRadius: 118,
  orbitalDistorterTapSlow: 0.28,
  orbitalDistorterTapDamageReduction: 0.28,
  orbitalDistorterTapMoveBoost: 1.16,
  orbitalDistorterTapMoveBoostDuration: 0.9,
  orbitalDistorterTapProjectileSlowEdge: 0.34,
  orbitalDistorterTapProjectileSlowCore: 0.58,
  orbitalDistorterHoldDuration: 2.5,
  orbitalDistorterHoldRadius: 176,
  orbitalDistorterHoldSlow: 0.34,
  orbitalDistorterHoldProjectileSlowEdge: 0.44,
  orbitalDistorterHoldProjectileSlowCore: 0.72,
  portalReuseCooldown: 10,
  vGripHarpoonCooldown: 5.6,
  vGripHarpoonRange: 620,
  vGripHarpoonWidth: 20,
  vGripHarpoonProjectileSpeed: 1360,
  vGripHarpoonProjectileRadius: 11,
  vGripHarpoonPullSpeed: 920,
  vGripHarpoonPullDistance: 170,
  vGripHarpoonSnare: 1,
  vGripHarpoonSnareDuration: 0.72,
  voidCoreSingularityCooldown: 6.2,
  voidCoreSingularityRadius: 126,
  voidCoreSingularityDuration: 2.4,
  voidCoreSingularitySlow: 0.26,
  voidCoreSingularityPullStrength: 124,
  reflexAegisStartup: 0.04,
  reflexAegisWindow: 1.2,
  reflexAegisFailRecovery: 0.15,
  reflexAegisCooldown: 9,
  reflexAegisShield: 18,
  reflexAegisShieldDuration: 2,
  reflexAegisMoveBonus: 0.2,
  reflexAegisMoveDuration: 1,
  reflexAegisHitBonusDamage: 14,
  reflexAegisHitBonusDuration: 1.5,
  reflexAegisTeleportOffset: 20,
  ghostDriftModuleCooldown: 7.2,
  ghostDriftModuleDuration: 0.62,
  shieldCooldown: 5.8,
  shieldValue: 24,
  shieldDuration: 2.2,
  shieldBreakRefund: 0.3,
  boosterCooldown: 6.5,
  ultimateCooldown: 14,
  phantomDuration: 4,
  phantomReplayDelay: 0.16,
  phantomActionDelay: 0.16,
  phantomDamageScale: 0.3,
  phantomHpScale: 0.3,
  phantomShieldScale: 0.3,
  phantomHealScale: 0.3,
  phantomStatusScale: 0.3,
  lancePrimaryRange: 228,
  lancePrimaryWidth: 18,
  lancePrimaryDamage: 44,
  lancePrimaryCooldown: 0.64,
  lancePrimarySlow: 0.24,
  lancePrimarySlowDuration: 0.28,
  lanceAltRange: 196,
  lanceAltWidth: 26,
  lanceAltDamage: 62,
  lanceAltCooldown: 1.06,
  lanceAltShockDuration: 0.42,
  cannonPrimaryDamage: 20,
  cannonPrimarySpeed: 760,
  cannonPrimaryCooldown: 0.92,
  cannonPrimaryRadius: 9,
  cannonSplashRadius: 84,
  cannonSplashDamage: 34,
  cannonBurnDuration: 1.8,
  cannonBurnMagnitude: 0.14,
  cannonMaxRange: 580,
  cannonChargeTime: 0.74,
  cannonAltDamage: 28,
  cannonAltSpeed: 640,
  cannonAltCooldown: 1.2,
  cannonAltRadius: 10,
  cannonFreezeDuration: 2.6,
  cannonFreezeMagnitude: 0.24,
  cannonChargedPushMax: 78,
  cannonChargedPushMin: 22,
  burnTickInterval: 0.45,
  burnTickDamage: 2.8,
  lastStandDuration: 3,
  lastStandMoveBonus: 0.22,
  lastStandHasteBonus: 0.28,
  precisionMomentumMaxStacks: 3,
  precisionMomentumDamagePerStack: 0.08,
  enemyRadius: 20,
  enemyMaxHp: 380,
  enemySpeed: 246,
  enemyDodgeSpeed: 780,
  enemyDodgeDuration: 0.17,
  enemyDodgeCooldown: 1.6,
  survivalWavePause: 2.1,
  survivalWaveIntermission: 3,
  runePoints: 15,
};

export const botDifficultyProfiles = {
  easy: {
    spreadMult: 1.42,
    damageMult: 0.76,
    cooldownMult: 1.28,
    dodgeChance: 0.52,
    reactionDelay: 0.14,
    abilityCooldownAdd: 1,
    aimLeadFactor: 0.04,
    strafeChangeRate: 0.6,
    dodgeReaction: 0.15,
    punishAwareness: 0.18,
    abilityTiming: 0.34,
    comboChaining: false,
    spacingAwareness: 0.42,
    defensiveReaction: 0.22,
    pressureAdaptation: 0.24,
    actionDelay: 0.24,
  },
  normal: {
    spreadMult: 1,
    damageMult: 1,
    cooldownMult: 1,
    dodgeChance: 1,
    reactionDelay: 0,
    abilityCooldownAdd: 0,
    aimLeadFactor: 0.16,
    strafeChangeRate: 1.4,
    dodgeReaction: 0.55,
    punishAwareness: 0.5,
    abilityTiming: 0.65,
    comboChaining: false,
    spacingAwareness: 0.75,
    defensiveReaction: 0.5,
    pressureAdaptation: 0.55,
    actionDelay: 0.12,
  },
  hard: {
    spreadMult: 0.72,
    damageMult: 1.12,
    cooldownMult: 0.82,
    dodgeChance: 1.2,
    reactionDelay: 0,
    abilityCooldownAdd: -0.4,
    aimLeadFactor: 0.3,
    strafeChangeRate: 2.8,
    dodgeReaction: 0.92,
    punishAwareness: 0.9,
    abilityTiming: 0.92,
    comboChaining: true,
    spacingAwareness: 0.95,
    defensiveReaction: 0.88,
    pressureAdaptation: 0.9,
    actionDelay: 0.03,
  },
  nightmare: {
    spreadMult: 0.5,
    damageMult: 1.25,
    cooldownMult: 0.68,
    dodgeChance: 1.45,
    reactionDelay: 0,
    abilityCooldownAdd: -0.8,
    aimLeadFactor: 0.38,
    strafeChangeRate: 3.4,
    dodgeReaction: 1,
    punishAwareness: 1,
    abilityTiming: 1,
    comboChaining: true,
    spacingAwareness: 1,
    defensiveReaction: 1,
    pressureAdaptation: 1,
    actionDelay: 0,
  },
};

export const sandboxModes = {
  duel: {
    key: "duel",
    name: "Arena (1v1)",
    subtitle: "One hunter bot, fair spawns, full duel behavior.",
  },
  teamDuel: {
    key: "teamDuel",
    name: "Arena (2v2)",
    subtitle: "Two allies versus two enemies. Team-based round combat.",
  },
  survival: {
    key: "survival",
    name: "Survival Mode",
    subtitle: "Escalating solo waves against adaptive hunter builds.",
  },
  training: {
    key: "training",
    name: "Training Lab",
    subtitle: "Static targets and instant rebuilds for values, spacing, and combo tests.",
  },
};

export const moduleConfig = {
  dash: {
    tapDuration: config.dashDuration,
    tapInvulnerability: config.dashInvulnerability,
    tapSpeed: config.dashSpeed,
    holdThreshold: 0.16,
    holdDuration: 0.28,
    holdInvulnerability: 0.34,
    holdSpeed: 1320,
    trailColor: "#9df4b7",
  },
  boltLinkJavelin: {
    cooldown: config.boltLinkJavelinCooldown,
    speed: config.boltLinkJavelinSpeed,
    damage: config.boltLinkJavelinDamage,
    radius: config.boltLinkJavelinRadius,
    range: config.boltLinkJavelinRange,
    slow: config.boltLinkJavelinSlow,
    slowDuration: config.boltLinkJavelinSlowDuration,
    recastDistance: config.boltLinkJavelinRecastDistance,
    color: "#8fe8ff",
    glow: "#d9fbff",
    trail: "#7ce5ff",
  },
  orbitalDistorter: {
    cooldown: config.orbitalDistorterCooldown,
    chargeThreshold: config.orbitalDistorterChargeThreshold,
    tap: {
      duration: config.orbitalDistorterTapDuration,
      radius: config.orbitalDistorterTapRadius,
      slow: config.orbitalDistorterTapSlow,
      damageReduction: config.orbitalDistorterTapDamageReduction,
      projectileSlowEdge: config.orbitalDistorterTapProjectileSlowEdge,
      projectileSlowCore: config.orbitalDistorterTapProjectileSlowCore,
      anchor: "player",
      color: "#89c8ff",
      glow: "#a8ddff",
    },
    hold: {
      duration: config.orbitalDistorterHoldDuration,
      radius: config.orbitalDistorterHoldRadius,
      slow: config.orbitalDistorterHoldSlow,
      damageReduction: 0,
      projectileSlowEdge: config.orbitalDistorterHoldProjectileSlowEdge,
      projectileSlowCore: config.orbitalDistorterHoldProjectileSlowCore,
      anchor: "world",
      color: "#95b5ff",
      glow: "#bed1ff",
    },
  },
  castTimes: {
    boltLinkJavelin: 0.18,
    swarmMissileRack: 0.15,
    railShot: 0.22,
    chainLightning: 0.16,
    voidCoreSingularity: 0.21,
    orbitalDistorter: 0.19,
    vGripHarpoon: 0.18,
  },
};

export const abilityConfig = moduleConfig;
