// Game content definitions (read-only data)
import { config } from "./config.js";

export const content = {
  avatars: {
    drifter: {
      key: "drifter",
      name: "Dust Drifter",
      description: "Rugged wasteland runner with patched plating and quick posture.",
      icon: "avatar-drifter",
      bodyColor: "#d9f3ff",
      accentColor: "#77d8ff",
      detailColor: "#593d23",
    },
    raider: {
      key: "raider",
      name: "Scrap Raider",
      description: "Aggressive pit-fighter silhouette with heavier rusted armor.",
      icon: "avatar-raider",
      bodyColor: "#ffe1ce",
      accentColor: "#ff8a77",
      detailColor: "#70422e",
    },
    voltborn: {
      key: "voltborn",
      name: "Voltborn",
      description: "Neon-charged arena killer wrapped in live cables and salvage tech.",
      icon: "avatar-voltborn",
      bodyColor: "#e6fff0",
      accentColor: "#8ff7da",
      detailColor: "#355643",
    },
    nomad: {
      key: "nomad",
      name: "Ash Nomad",
      description: "Lean desert scavenger with a stark silhouette and bone-white plating.",
      icon: "avatar-nomad",
      bodyColor: "#f4f0df",
      accentColor: "#ffd375",
      detailColor: "#65593c",
    },
    warhound: {
      key: "warhound",
      name: "Warhound",
      description: "Pit veteran wrapped in bolted plate, cable scars, and a mean heavy stance.",
      icon: "avatar-warhound",
      bodyColor: "#d6d2cf",
      accentColor: "#ff9a6a",
      detailColor: "#473a33",
    },
    ghostwire: {
      key: "ghostwire",
      name: "Ghostwire",
      description: "Lean neon tracker with a surgical visor and high-voltage spine rig.",
      icon: "avatar-ghostwire",
      bodyColor: "#e1fbff",
      accentColor: "#5cf7ff",
      detailColor: "#314750",
    },
    ironmaw: {
      key: "ironmaw",
      name: "Ironmaw",
      description: "Scrap juggernaut silhouette with asymmetrical armor and brutal edge plating.",
      icon: "avatar-ironmaw",
      bodyColor: "#f0dccf",
      accentColor: "#ff7b54",
      detailColor: "#5a342c",
    },
    dunepriest: {
      key: "dunepriest",
      name: "Dune Priest",
      description: "Dust-robed tech mystic carrying jury-rigged coils and ritual glow strips.",
      icon: "avatar-dunepriest",
      bodyColor: "#ede8d7",
      accentColor: "#a8f7c0",
      detailColor: "#5f5642",
    },
  },
  weaponSkins: {
    stock: {
      key: "stock",
      name: "Stock Steel",
      description: "Factory-scrap baseline with clean cyan optics.",
      icon: "skin-stock",
      tint: "#77d8ff",
      glow: "#dff7ff",
    },
    rustfang: {
      key: "rustfang",
      name: "Rustfang",
      description: "Orange scorched metal and brutal junkyard accents.",
      icon: "skin-rustfang",
      tint: "#ff9a6a",
      glow: "#ffd0b1",
    },
    shockglass: {
      key: "shockglass",
      name: "Shockglass",
      description: "Electric teal edge with bright glass-core highlights.",
      icon: "skin-shockglass",
      tint: "#8ff7da",
      glow: "#d9fff5",
    },
    wastelux: {
      key: "wastelux",
      name: "Wastelux",
      description: "Gold-white prestige shell made from reclaimed arena parts.",
      icon: "skin-wastelux",
      tint: "#ffd375",
      glow: "#fff3cc",
    },
    bloodwire: {
      key: "bloodwire",
      name: "Bloodwire",
      description: "Red-hot copper weave wrapped around savage scrapyard housings.",
      icon: "skin-bloodwire",
      tint: "#ff6f63",
      glow: "#ffd2c8",
    },
    toxicash: {
      key: "toxicash",
      name: "Toxic Ash",
      description: "Acid-green salvage finish built from refinery waste and irradiated dust.",
      icon: "skin-toxicash",
      tint: "#b0ff77",
      glow: "#e7ffd3",
    },
    voidchrome: {
      key: "voidchrome",
      name: "Voidchrome",
      description: "Matte black frame with violent magenta edge lights and dead-cold chrome.",
      icon: "skin-voidchrome",
      tint: "#dd8cff",
      glow: "#f2d2ff",
    },
  },
  weapons: {
    pulse: {
      key: "pulse",
      name: "Pulse Rifle",
      cooldown: config.fireRate,
      slotLabel: "Ranged Pressure",
      description: "Reliable ranged control with steady pressure and fast rhythm.",
      rhythm: "Fast",
      rangeProfile: "Medium / long lane control",
      commitment: "Low",
      accent: "#77d8ff",
      icon: "weapon-pulse",
      category: "offense",
      state: "playable",
    },
    axe: {
      key: "axe",
      name: "Electro Axe",
      cooldown: 0.24,
      slotLabel: "Heavy Melee",
      description: "Three-hit heavy melee chain: long opener, tight cleave, then a stun dash finisher that must connect cleanly.",
      rhythm: "Slow / committed",
      rangeProfile: "Long opener, short cleave, dash finisher",
      commitment: "High",
      accent: "#8ff7da",
      icon: "weapon-axe",
      category: "offense",
      state: "playable",
    },
    shotgun: {
      key: "shotgun",
      name: "Scrap Shotgun",
      cooldown: 0.52,
      slotLabel: "Close Burst",
      description: "High-risk blast weapon with brutal close damage and weak long pressure.",
      rhythm: "Burst / reload feel",
      rangeProfile: "Close",
      commitment: "Medium",
      accent: "#ff9d62",
      icon: "weapon-shotgun",
      category: "offense",
      state: "playable",
    },
    sniper: {
      key: "sniper",
      name: "Rail Sniper",
      cooldown: config.sniperBaseCooldown,
      slotLabel: "Precision",
      description: "Hold to charge, punish at range, and spike harder the farther the shot travels.",
      rhythm: "Charge / punish",
      rangeProfile: "Long lane control / distance finisher",
      commitment: "High",
      accent: "#ffd375",
      icon: "weapon-sniper",
      category: "offense",
      state: "playable",
    },
    staff: {
      key: "staff",
      name: "Volt Staff",
      cooldown: 0.42,
      slotLabel: "Sustain Hybrid",
      description: "Hybrid beam staff that trades raw DPS for sustain and support value.",
      rhythm: "Measured / sustain",
      rangeProfile: "Medium",
      commitment: "Medium",
      accent: "#95ffb4",
      icon: "weapon-staff",
      category: "support",
      state: "playable",
    },
    injector: {
      key: "injector",
      name: "Bio-Injector Gun",
      cooldown: 0.26,
      slotLabel: "Mark Utility",
      description: "Strange salvage-tech gun that turns pressure into sustain through marks.",
      rhythm: "Stack / convert",
      rangeProfile: "Medium",
      commitment: "Low",
      accent: "#d88cff",
      icon: "weapon-injector",
      category: "utility",
      state: "playable",
    },
    lance: {
      key: "lance",
      name: "Charge Lance",
      cooldown: config.lancePrimaryCooldown,
      slotLabel: "Engage Bruiser",
      description: "Long thrust bruiser weapon with an electrified drive on alt-fire.",
      rhythm: "Measured / engage",
      rangeProfile: "Mid reach thrust into short burst commit",
      commitment: "High",
      accent: "#ffe27c",
      icon: "weapon-lance",
      category: "offense",
      state: "playable",
    },
    cannon: {
      key: "cannon",
      name: "Heavy Cannon",
      cooldown: config.cannonPrimaryCooldown,
      slotLabel: "Siege Burst",
      description: "Slow shell launcher with splash pressure and a cryo control alt-fire.",
      rhythm: "Slow / explosive",
      rangeProfile: "Medium / long siege",
      commitment: "High",
      accent: "#ffb16a",
      icon: "weapon-cannon",
      category: "control",
      state: "playable",
    },
  },
  abilities: {
    vectorDash: {
      key: "vectorDash",
      name: "Vector Dash",
      input: "Shift",
      role: "Mobility / Outplay",
      description: "Legacy build entry. Dash is now a universal core mechanic for every build.",
      icon: "ability-dash",
      category: "mobility",
      state: "locked",
    },
    blinkStep: { key: "blinkStep", name: "Blink Step", role: "Mobility", description: "Short displacement burst.", icon: "ability-blink", category: "mobility", state: "playable" },
    magneticGrapple: {
      key: "magneticGrapple",
      name: "Magnetic Grapple",
      input: "Q",
      role: "Engage / Catch",
      description: "Catch an enemy on a narrow line, drag them into punish range, and briefly snare them.",
      icon: "ability-grapple",
      category: "mobility",
      state: "playable",
    },
    phaseDash: { key: "phaseDash", name: "Phase Dash", role: "Mobility", description: "Untargetable phase burst.", icon: "ability-phase", category: "mobility", state: "playable" },
    slideBooster: { key: "slideBooster", name: "Slide Booster", role: "Mobility", description: "Ground slide for spacing.", icon: "ability-slide", category: "mobility", state: "locked" },
    backstepBurst: { key: "backstepBurst", name: "Backstep Burst", role: "Mobility", description: "Fast reverse burst that creates breathing room without killing tempo.", icon: "ability-backstep", category: "mobility", state: "playable" },
    jetLeap: { key: "jetLeap", name: "Jet Leap", role: "Mobility", description: "Short leap with air drift.", icon: "ability-jump", category: "mobility", state: "locked" },
    markReturn: { key: "markReturn", name: "Mark-and-Return Teleport", role: "Mobility", description: "Set a return point then snap back.", icon: "ability-return", category: "mobility", state: "locked" },
    shockJavelin: {
      key: "shockJavelin",
      name: "Shock Javelin",
      input: "Q",
      role: "Punish / Combo",
      description: "Fast punish on tap, charged control hit on hold.",
      icon: "ability-javelin",
      category: "offense",
      state: "playable",
    },
    pulseBurst: { key: "pulseBurst", name: "Pulse Burst", role: "Offense", description: "Short-range burst of pulse shots.", icon: "ability-burst", category: "offense", state: "playable" },
    railShot: { key: "railShot", name: "Rail Shot", role: "Offense", description: "Charged piercing line shot.", icon: "ability-rail", category: "offense", state: "playable" },
    chainLightning: { key: "chainLightning", name: "Chain Lightning", role: "Offense", description: "Snap a primary target, then arc into nearby bodies for tempo pressure.", icon: "ability-chain", category: "offense", state: "playable" },
    plasmaCone: { key: "plasmaCone", name: "Plasma Cone", role: "Offense", description: "Short cone blast for close pressure.", icon: "ability-cone", category: "offense", state: "locked" },
    returningBlade: { key: "returningBlade", name: "Returning Energy Blade", role: "Offense", description: "Boomerang pressure projectile.", icon: "ability-blade", category: "offense", state: "locked" },
    magneticMine: { key: "magneticMine", name: "Magnetic Mine", role: "Offense", description: "Trap mine with pull effect.", icon: "ability-mine", category: "offense", state: "locked" },
    delayedOrb: { key: "delayedOrb", name: "Delayed Pulse Orb", role: "Offense", description: "Orb that detonates on delay.", icon: "ability-orb", category: "offense", state: "locked" },
    shortLaser: { key: "shortLaser", name: "Short Laser Beam", role: "Offense", description: "Brief tracking beam.", icon: "ability-laser", category: "offense", state: "locked" },
    scatterBlast: { key: "scatterBlast", name: "Scatter Blast", role: "Offense", description: "Wide multi-fragment shot.", icon: "ability-scatter", category: "offense", state: "locked" },
    autoTurret: { key: "autoTurret", name: "Auto-Turret Drone", role: "Offense", description: "Deploy small pressure drone.", icon: "ability-turret", category: "offense", state: "locked" },
    fragmentGrenade: { key: "fragmentGrenade", name: "Fragment Grenade", role: "Offense", description: "Simple explosive zoning tool.", icon: "ability-grenade", category: "offense", state: "locked" },
    magneticField: {
      key: "magneticField",
      name: "Magnetic Field",
      input: "F",
      role: "Defense / Control",
      description: "Projectile denial and space control for reset or setup.",
      icon: "ability-field",
      category: "control",
      state: "playable",
    },
    gravityWell: { key: "gravityWell", name: "Gravity Well", role: "Control", description: "Pull field that punishes spacing.", icon: "ability-gravity", category: "control", state: "playable" },
    shockwavePush: { key: "shockwavePush", name: "Shockwave Push", role: "Control", description: "Knockback pulse for disengage.", icon: "ability-push", category: "control", state: "locked" },
    rootTrap: { key: "rootTrap", name: "Root Trap", role: "Control", description: "Ground trap that roots targets.", icon: "ability-root", category: "control", state: "locked" },
    silencePulse: { key: "silencePulse", name: "Silence Pulse", role: "Control", description: "Short anti-cast pulse.", icon: "ability-silence", category: "control", state: "locked" },
    empBurst: {
      key: "empBurst",
      name: "EMP Burst",
      input: "F",
      role: "Control / Utility",
      description: "Disrupt nearby projectiles and briefly weaken the enemy.",
      icon: "ability-emp",
      category: "control",
      state: "playable",
    },
    mobileSlowField: { key: "mobileSlowField", name: "Mobile Slow Field", role: "Control", description: "Field that follows the caster.", icon: "ability-mobilefield", category: "control", state: "locked" },
    tetherLink: { key: "tetherLink", name: "Tether Link", role: "Control", description: "Link target to movement tax.", icon: "ability-tether", category: "control", state: "locked" },
    energyShield: {
      key: "energyShield",
      name: "Energy Shield",
      input: "F",
      role: "Defense",
      description: "Deploy a compact shield buffer for short defensive windows.",
      icon: "ability-shield",
      category: "defense",
      state: "playable",
    },
    phaseShift: { key: "phaseShift", name: "Phase Shift", role: "Defense", description: "Brief intangibility window.", icon: "ability-phaseshift", category: "defense", state: "playable" },
    healPulse: { key: "healPulse", name: "Heal Pulse", role: "Defense", description: "Short combat heal burst.", icon: "ability-heal", category: "defense", state: "locked" },
    regenZone: { key: "regenZone", name: "Regen Zone", role: "Defense", description: "Zone that restores health over time.", icon: "ability-regen", category: "defense", state: "locked" },
    reflectBarrier: { key: "reflectBarrier", name: "Reflect Barrier", role: "Defense", description: "Reflects incoming fire briefly.", icon: "ability-reflect", category: "defense", state: "locked" },
    damageReductionAura: { key: "damageReductionAura", name: "Damage Reduction Aura", role: "Defense", description: "Short mitigation aura.", icon: "ability-aura", category: "defense", state: "locked" },
    overdriveBooster: {
      key: "overdriveBooster",
      name: "Overdrive Booster",
      input: "F",
      role: "Utility / Tempo",
      description: "Legacy ability retired from the competitive ruleset.",
      icon: "ability-booster",
      category: "utility",
      state: "locked",
    },
    cooldownReset: { key: "cooldownReset", name: "Partial Cooldown Reset", role: "Utility", description: "Shave time off active cooldowns.", icon: "ability-reset", category: "utility", state: "locked" },
    visionScan: { key: "visionScan", name: "Vision Scan", role: "Utility", description: "Read enemy position and intent.", icon: "ability-scan", category: "utility", state: "locked" },
    hologramDecoy: { key: "hologramDecoy", name: "Hologram Decoy", role: "Utility", description: "Spawn a false target to break focus.", icon: "ability-decoy", category: "utility", state: "playable" },
    speedSurge: { key: "speedSurge", name: "Speed Surge", role: "Utility", description: "Flat movement burst for tempo.", icon: "ability-speed", category: "utility", state: "playable" },
    resourceConverter: { key: "resourceConverter", name: "Resource Converter", role: "Utility", description: "Convert pressure into energy or sustain.", icon: "ability-convert", category: "utility", state: "locked" },
  },
  perks: {
    omnivampCore: { key: "omnivampCore", name: "Omnivamp Core", description: "Heal slightly from damage dealt.", icon: "perk-vamp", state: "playable" },
    executionRelay: { key: "executionRelay", name: "Execution Relay", description: "Deal bonus damage to slowed targets.", icon: "perk-execution", state: "playable" },
    adrenalSurge: { key: "adrenalSurge", name: "Adrenal Surge", description: "Gain attack speed after using mobility.", icon: "perk-adrenal", state: "playable" },
    predatorInstinct: { key: "predatorInstinct", name: "Predator Instinct", description: "Low-health targets take more damage.", icon: "perk-predator", state: "playable" },
    comboDriver: { key: "comboDriver", name: "Combo Driver", description: "Electro Axe finisher hits harder.", icon: "perk-combo", state: "playable" },
    scavengerPlates: { key: "scavengerPlates", name: "Scavenger Plates", description: "Increase max HP.", icon: "perk-plates", state: "playable" },
    reactiveArmor: { key: "reactiveArmor", name: "Reactive Armor", description: "Reduce incoming damage.", icon: "perk-armor", state: "playable" },
    combatRecovery: { key: "combatRecovery", name: "Combat Recovery", description: "Recover health when disengaged.", icon: "perk-recovery", state: "playable" },
    shockBuffer: { key: "shockBuffer", name: "Shock Buffer", description: "Reduce crowd-control duration.", icon: "perk-buffer", state: "playable" },
    lastStandBuffer: { key: "lastStandBuffer", name: "Last Stand Buffer", description: "Once per round survive fatal damage.", icon: "perk-laststand", state: "playable" },
    dashCooling: { key: "dashCooling", name: "Dash Cooling", description: "Reduce dash cooldown.", icon: "perk-cooling", state: "playable" },
    ghostCircuit: { key: "ghostCircuit", name: "Ghost Circuit", description: "Brief phasing after dash.", icon: "perk-ghost", state: "playable" },
    overdriveCapacitor: { key: "overdriveCapacitor", name: "Overdrive Capacitor", description: "Legacy perk retired from the competitive ruleset.", icon: "perk-capacitor", state: "locked" },
    abilityLeech: { key: "abilityLeech", name: "Ability Leech", description: "Ability hits restore a little health.", icon: "perk-leech", state: "playable" },
    staticMomentum: { key: "staticMomentum", name: "Static Momentum", description: "Applying control grants speed.", icon: "perk-momentum", state: "playable" },
    tacticalHaste: { key: "tacticalHaste", name: "Tactical Haste", description: "Ability hits grant a short haste.", icon: "perk-haste", state: "playable" },
    cloneFailover: { key: "cloneFailover", name: "Clone Failover", description: "Emergency decoy at low HP.", icon: "perk-clone", state: "playable" },
    arcFeedback: { key: "arcFeedback", name: "Arc Feedback", description: "Burst damage grants a small shield.", icon: "perk-feedback", state: "playable" },
    overclockTrigger: { key: "overclockTrigger", name: "Overclock Trigger", description: "Legacy perk retired from the competitive ruleset.", icon: "perk-trigger", state: "locked" },
    utilityBattery: { key: "utilityBattery", name: "Utility Battery", description: "Defensive and support actions restore combat value.", icon: "perk-battery", state: "playable" },
  },
  ultimates: {
    overdriveOverload: {
      key: "overdriveOverload",
      name: "Overdrive Overload",
      description: "Legacy ultimate retired from the competitive ruleset.",
      icon: "ultimate-overload",
      state: "locked",
    },
    arenaLockdown: {
      key: "arenaLockdown",
      name: "Arena Lockdown",
      description: "Future arena-control ultimate that narrows the duel space.",
      icon: "ultimate-lockdown",
      state: "playable",
    },
    phantomSplit: {
      key: "phantomSplit",
      name: "Phantom Split",
      description: "Forge a live clone that echoes your actions at reduced power and scrambles enemy target reads.",
      icon: "ultimate-phantom",
      state: "playable",
    },
    empCataclysm: {
      key: "empCataclysm",
      name: "EMP Cataclysm",
      description: "Future anti-tech collapse burst.",
      icon: "ultimate-emp",
      state: "playable",
    },
    berserkCore: {
      key: "berserkCore",
      name: "Berserk Core",
      description: "Future aggression and sustain window.",
      icon: "ultimate-berserk",
      state: "playable",
    },
    revivalProtocol: {
      key: "revivalProtocol",
      name: "Revival Protocol",
      description: "Prime a failsafe that rescues you from lethal damage once.",
      icon: "ultimate-revival",
      state: "playable",
    },
  },
  runeTrees: {
    attack: {
      key: "attack",
      name: "Attack",
      description: "Higher damage, faster payoff, and better finisher scaling.",
      nodes: {
        secondary: {
          key: "secondary",
          name: "Sharpened Current",
          description: "+damage, +attack speed, and precision bonus.",
          max: 5,
        },
        primary: {
          key: "primary",
          name: "Predator Tempo",
          description: "Hitting enemies grants a short offensive buff and stronger combo finishers.",
          max: 3,
        },
        ultimate: {
          key: "ultimate",
          name: "Execution Surge",
          description: "Low-health targets trigger a brief combat surge and a stronger finishing window.",
          max: 1,
        },
      },
    },
    defense: {
      key: "defense",
      name: "Defense",
      description: "Toughness, burst resistance, and recovery from pressure.",
      nodes: {
        secondary: {
          key: "secondary",
          name: "Composite Plating",
          description: "+max HP, +damage reduction, and reduced control duration.",
          max: 5,
        },
        primary: {
          key: "primary",
          name: "Recovery Loop",
          description: "Abilities restore a little health and burst damage can trigger a brief shield.",
          max: 3,
        },
        ultimate: {
          key: "ultimate",
          name: "Last Stand Capacitor",
          description: "Once per round, lethal damage leaves you alive or grants a strong low-HP shield.",
          max: 1,
        },
      },
    },
    spells: {
      key: "spells",
      name: "Spells",
      description: "Cooldown pressure, stronger ability flow, and cleaner status timing.",
      nodes: {
        secondary: {
          key: "secondary",
          name: "Quickcharge Weave",
          description: "Cooldown reduction and slightly longer status effects.",
          max: 5,
        },
        primary: {
          key: "primary",
          name: "Chain Casting",
          description: "Ability hits grant short haste and one ability can empower the next.",
          max: 3,
        },
        ultimate: {
          key: "ultimate",
          name: "Arc Script",
          description: "Charged abilities gain a stronger competitive payoff.",
          max: 1,
        },
      },
    },
    support: {
      key: "support",
      name: "Support",
      description: "Utility, control value, and movement-oriented tempo.",
      nodes: {
        secondary: {
          key: "secondary",
          name: "Vector Utility",
          description: "+movement speed, faster recovery, and stronger utility durations.",
          max: 5,
        },
        primary: {
          key: "primary",
          name: "Momentum Relay",
          description: "Applying control grants a self-buff and dash usage creates utility windows.",
          max: 3,
        },
        ultimate: {
          key: "ultimate",
          name: "Command Uplink",
          description: "Control actions build toward a utility surge and stronger clutch mobility.",
          max: 1,
        },
      },
    },
  },
};


export const weapons = content.weapons;

export const statusVisuals = {
  slow: {
    label: "SLOW",
    fill: "rgba(111, 226, 255, 0.95)",
    stroke: "rgba(199, 245, 255, 0.9)",
    text: "#97efff",
    wave: "ring",
  },
  stun: {
    label: "STUN!",
    fill: "rgba(255, 86, 64, 0.98)",
    stroke: "rgba(255, 234, 214, 0.96)",
    text: "#ffd8b8",
    wave: "spark",
  },
  burn: {
    label: "BURN",
    fill: "rgba(255, 144, 92, 0.96)",
    stroke: "rgba(255, 223, 189, 0.94)",
    text: "#ffb993",
    wave: "spark",
  },
  freeze: {
    label: "FREEZE",
    fill: "rgba(171, 228, 255, 0.96)",
    stroke: "rgba(236, 251, 255, 0.96)",
    text: "#c8f2ff",
    wave: "ring",
  },
  shock: {
    label: "SHOCK",
    fill: "rgba(255, 228, 143, 0.96)",
    stroke: "rgba(255, 248, 209, 0.96)",
    text: "#fff2b8",
    wave: "spark",
  },
  snare: {
    label: "SNARE",
    fill: "rgba(181, 235, 255, 0.96)",
    stroke: "rgba(229, 248, 255, 0.96)",
    text: "#c7edff",
    wave: "ring",
  },
};
