// DOM element references
export const canvas = document.getElementById("game");
export const ctx = canvas.getContext("2d");
export const gameShell = document.querySelector(".game-shell");

if (!canvas || !ctx) {
  throw new Error("Canvas initialization failed.");
}


export const weaponStatus = document.getElementById("weapon-status");
export const weaponName = document.getElementById("weapon-name");
export const weaponIcon = document.getElementById("weapon-icon");
export const mapName = document.getElementById("map-name");
export const mapStatus = document.getElementById("map-status");
export const helpToggle = document.getElementById("help-toggle");
export const helpPanel = document.getElementById("help-panel");
export const roundLabel = document.getElementById("round-label");
export const matchScore = document.getElementById("match-score");
export const matchFormat = document.getElementById("match-format");
export const roundBanner = document.getElementById("round-banner");
export const roundBannerLabel = document.getElementById("round-banner-label");
export const roundBannerTitle = document.getElementById("round-banner-title");
export const statusLine = document.getElementById("status-line");
export const weaponMeter = document.getElementById("weapon-meter");
export const playerHealthFill = document.getElementById("player-health-fill");
export const enemyHealthFill = document.getElementById("enemy-health-fill");
export const playerHealthText = document.getElementById("player-health-text");
export const enemyHealthText = document.getElementById("enemy-health-text");
export const menuButton = document.getElementById("menu-button");
export const rematchButton = document.getElementById("rematch-button");
export const audioPanel = document.getElementById("audio-panel");
export const audioMuteButton = document.getElementById("audio-mute-button");
export const audioMusicVolume = document.getElementById("audio-music-volume");
export const audioSfxVolume = document.getElementById("audio-sfx-volume");
export const audioAmbienceVolume = document.getElementById("audio-ambience-volume");
export const hudMenuButton = document.getElementById("hud-menu-button");
export const hudRematchButton = document.getElementById("hud-rematch-button");
export const moveJoystick = document.getElementById("move-joystick");
export const moveStick = document.getElementById("move-stick");
export const slotDash = document.getElementById("slot-dash");
export const slotDashIcon = slotDash.querySelector(".ability-slot__icon");
export const slotDashName = slotDash.querySelector(".ability-slot__name");
export const slotDashOverlay = document.getElementById("slot-dash-overlay");
export const slotDashTimer = document.getElementById("slot-dash-timer");
export const slotAbility1 = document.getElementById("slot-ability-1");
export const slotAbility1Icon = slotAbility1.querySelector(".ability-slot__icon");
export const slotAbility1Name = slotAbility1.querySelector(".ability-slot__name");
export const slotAbility1Overlay = document.getElementById("slot-ability-1-overlay");
export const slotAbility1Timer = document.getElementById("slot-ability-1-timer");
export const slotAbility2 = document.getElementById("slot-ability-2");
export const slotAbility2Icon = slotAbility2.querySelector(".ability-slot__icon");
export const slotAbility2Name = slotAbility2.querySelector(".ability-slot__name");
export const slotAbility2Overlay = document.getElementById("slot-ability-2-overlay");
export const slotAbility2Timer = document.getElementById("slot-ability-2-timer");
export const slotAbility3 = document.getElementById("slot-ability-3");
export const slotAbility3Icon = slotAbility3.querySelector(".ability-slot__icon");
export const slotAbility3Name = slotAbility3.querySelector(".ability-slot__name");
export const slotAbility3Overlay = document.getElementById("slot-ability-3-overlay");
export const slotAbility3Timer = document.getElementById("slot-ability-3-timer");
export const ultimateSlot = document.getElementById("slot-ultimate");
export const ultimateSlotIcon = ultimateSlot.querySelector(".ability-slot__icon");
export const ultimateSlotName = ultimateSlot.querySelector(".ability-slot__name");
export const ultimateSlotOverlay = document.getElementById("slot-ultimate-overlay");
export const ultimateSlotTimer = document.getElementById("slot-ultimate-timer");
export const prematchOverlay = document.getElementById("prematch-overlay");
export const modeScreen = document.getElementById("mode-screen");
export const mapScreen = document.getElementById("map-screen");
export const buildScreen = document.getElementById("build-screen");
export const stepMode = document.getElementById("step-mode");
export const stepMap = document.getElementById("step-map");
export const stepBuild = document.getElementById("step-build");
export const modeDuel = document.getElementById("mode-duel");
export const modeSurvival = document.getElementById("mode-survival");
export const modeTraining = document.getElementById("mode-training");
export const mapGrid = document.getElementById("map-grid");
export const continueMap = document.getElementById("continue-map");
export const continueBuild = document.getElementById("continue-build");
export const backMode = document.getElementById("back-mode");
export const backMap = document.getElementById("back-map");
export const startSession = document.getElementById("start-session");
export const prematchDescription = document.getElementById("prematch-description");
export const selectedModeLabel = document.getElementById("selected-mode-label");
export const selectedMapLabel = document.getElementById("selected-map-label");
export const selectedWeaponLabel = document.getElementById("selected-weapon-label");
export const runePointsLabel = document.getElementById("rune-points-label");
export const runePointsInline = document.getElementById("rune-points-inline");
export const runeUltimateInline = document.getElementById("rune-ultimate-inline");
export const avatarOptions = document.getElementById("avatar-options");
export const weaponSkinOptions = document.getElementById("weapon-skin-options");
export const runeGrid = document.getElementById("rune-grid");
export const buildLibraryGrid = document.getElementById("build-library-grid");
export const detailIcon = document.getElementById("detail-icon");
export const detailName = document.getElementById("detail-name");
export const detailMeta = document.getElementById("detail-meta");
export const detailDescription = document.getElementById("detail-description");
export const detailFloat = document.getElementById("detail-float");
export const powerOffense = document.getElementById("power-offense");
export const powerDefense = document.getElementById("power-defense");
export const powerUtility = document.getElementById("power-utility");
export const powerControl = document.getElementById("power-control");
export const cosmeticPreviewName = document.getElementById("cosmetic-preview-name");
export const cosmeticAvatarPreview = document.getElementById("cosmetic-avatar-preview");
export const cosmeticWeaponIcon = document.getElementById("cosmetic-weapon-icon");
export const cosmeticWeaponName = document.getElementById("cosmetic-weapon-name");
export const cosmeticWeaponCopy = document.getElementById("cosmetic-weapon-copy");
export const labTabLoadout = document.getElementById("lab-tab-loadout");
export const labTabStyle = document.getElementById("lab-tab-style");
export const labLoadout = document.getElementById("lab-loadout");
export const labStyle = document.getElementById("lab-style");
export const runePanel = document.getElementById("rune-panel");
export const botConfigToggle = document.getElementById("bot-config-toggle");
export const botConfigCard = document.getElementById("bot-config-card");
export const botConfigLabel = document.getElementById("bot-config-label");
export const botConfigTitle = document.getElementById("bot-config-title");
export const botConfigCopy = document.getElementById("bot-config-copy");
export const botConfigDuel = document.getElementById("bot-config-duel");
export const botConfigTraining = document.getElementById("bot-config-training");
export const botModeRandom = document.getElementById("bot-mode-random");
export const botModeCustom = document.getElementById("bot-mode-custom");
export const botWeaponGrid = document.getElementById("bot-weapon-grid");
export const botAbilityGrid = document.getElementById("bot-ability-grid");
export const botBuildSummary = document.getElementById("bot-build-summary");
export const trainingFireOff = document.getElementById("training-fire-off");
export const trainingFireOn = document.getElementById("training-fire-on");
export const trainingBuildSummary = document.getElementById("training-build-summary");
export const buildStepPrev = document.getElementById("build-step-prev");
export const buildStepNext = document.getElementById("build-step-next");
export const runeScreen = document.getElementById("rune-screen");
export const continueRunes = document.getElementById("continue-runes");
export const backBuild = document.getElementById("back-build");
export const runeResetButton = document.getElementById("rune-reset-btn");
export const libraryTabs = Array.from(document.querySelectorAll("[data-library]"));
export const loadoutSlotButtons = {
  weapon: document.getElementById("loadout-slot-weapon"),
  ability0: document.getElementById("loadout-slot-ability-0"),
  ability1: document.getElementById("loadout-slot-ability-1"),
  ability2: document.getElementById("loadout-slot-ability-2"),
  perk0: document.getElementById("loadout-slot-perk-0"),
  ultimate: document.getElementById("loadout-slot-ultimate"),
};

